### ISSUE TITLE
Post closes when focus is lost on iPhone

### ISSUE THREAD

**Issue by AntonOellerer** [writefreely/writefreely-swiftui-multiplatform#256]
Hey,
First of all, thank you very much for WriteFreely and the iOs App, I have been using it to keep my family up-to-date with my travels for five months now, with great success!

When using the application on my iPhone SE 2nd generation (iOs 17.3), I noticed that whenever the focus changes away from the application while editing a post, the post closes.
In a bit more detail:

# Steps to Reproduce:
1. Create new post
2. Write some text
3. Pull up iOs quick settings
4. Close quick settings

# Expected behaviour
Post is still open, ready to be edited

# Actual behaviour
Post is closed

**Comment by AngeloStavrow** [comment]
@AntonOellerer thanks for reporting this bug — I'm working on a fix. Glad to hear you're finding the app helpful on your travels!

**Comment by AngeloStavrow** [comment]
Okay, after a _lot_ of debugging, I've figured out _why_ this is happening in iOS 17.

In the PostListView —the screen that shows the list of posts— there's [an `onReceive` modifier](https://github.com/writefreely/writefreely-swiftui-multiplatform/blob/664eb44882d020c14893f0b645b50a884ece7804/Shared/PostList/PostListView.swift#L129-L135) that listens for when the app has become active:

```swift
.onReceive(NotificationCenter.default.publisher(for: UIApplication.didBecomeActiveNotification)) { _ in
    // We use this to invalidate and refresh the view, so that new posts created outside of the app (e.g.,
    // in the action extension) show up.
    withAnimation {
        self.filteredListViewId += 1
    }
}
```

As the comment suggests, we use this to force the app to refresh the list. This was added when we added the Safari extension that lets you create a new local draft from selected text on a webpage, so that if you returned to the app the list would reload and show the new, extension-created local draft.

Commenting out this code fixes the bug you reported, but breaks the ability to refresh the list of posts when the app becomes active. I'm investigating to see why this broke in iOS 17, when it was working as expected previously. 🤔
